const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const game = fs.readFileSync(path.join(__dirname, "../src/game.js"), "utf8");
const html = fs.readFileSync(path.join(__dirname, "../index.html"), "utf8");
const zombieIds = ["basic", "cone", "bucket", "runner", "paper", "shield", "healer", "football", "balloon", "miner", "dancer", "giant", "imp", "ice", "pole", "flyer"];

assert.match(game, /const BASE_WAVE_SECONDS = 30;/);
assert.match(game, /const SPAWN_GAPS = \[9\.8,9\.2,8\.6,8,7\.4,6\.8,6\.2,5\.7,5\.2,4\.8\];/);
assert.match(game, /state\.zombies\.length<48/);
assert.match(game, /Math\.max\(2\.7,base\*endless\)/);
assert.match(game, /function drawTextEntity\(/);
assert.match(game, /classic-lawn-background\.jpg/);
assert.match(game, /const GRID = \{ x: 259, y: 86, cols: 9, rows: 5, cw: 96\.25, ch: 120\.25 \};/);
assert.doesNotMatch(game, /\(r\+c\)%2/);
assert.match(game, /function drawPlacementPreview\(\)/);
assert.match(game, /"种植预览"/);
assert.match(game, /const ZOMBIE_TEXT=/);
assert.match(game, /我是小推车/);
assert.match(game, /我是阳光/);
assert.match(game, /mowers: \[1,1,1,1,1\]/);
assert.doesNotMatch(game, /补充了一次推土机机会/);
assert.match(game, /spawnTimer: 10/);
assert.match(game, /state\.mowers\[z\.row\]--/);
assert.match(game, /function poolForWave\(wave\)/);
assert.match(game, /state\.gameMode==="classic"&&state\.battleTime>=WAVE_SECONDS\*10/);
assert.match(game, /function winClassic\(\)/);
for (const id of zombieIds) assert.match(game, new RegExp(`${id}:\\{hp:`), `missing zombie definition: ${id}`);
assert.match(game, /const ZOMBIE_POOLS=\[/);
assert.match(game, /const LOADOUT_SIZE = 10;/);
assert.match(game, /confirmPlantsBtn\.disabled=count===0/);
assert.match(game, /pendingLoadout\.length<1\|\|pendingLoadout\.length>LOADOUT_SIZE/);
assert.match(game, /potato:"◆"/);
assert.match(game, /umbrella:"☂"/);
assert.match(game, /for\(let i=0;i<state\.loadout\.length;i\+\+\)/);
assert.match(game, /data-game-mode/);
assert.match(game, /plant && state\.selected/);
assert.match(game, /function fuseSelectedInto\(host\)/);
assert.match(game, /Core\.previewFusion\(donor,host\)/);
assert.match(game, /wave<=ZOMBIE_POOLS\.length/);
assert.match(game, /kind==="pole"&&!z\.vaulted&&target\.baseId!=="tallnut"/);
assert.match(game, /if\(target&&z\.kind==="giant"\)/);
assert.match(game, /z\.slam<=\.56/);
assert.match(game, /dragCell/);
assert.match(game, /function globalFreeze\(/);
assert.match(game, /function supportPulse\(/);
assert.match(game, /Array\.from\(\{length:5\},\(_,i\)=>-Math\.PI\/2\+i\*TAU\/5\)/);
assert.match(game, /function updateGloom\(p,dt,hasEnemy\)/);
assert.match(game, /function updateFume\(p,hasEnemy\)/);
assert.match(game, /p\.baseId==="fume"/);
assert.match(game, /z\.row===p\.row&&z\.x>=c\.x-10/);
assert.match(game, /type:"gasRow"/);
assert.match(game, /p\.gloomShotsLeft=3/);
assert.match(game, /p\.gloomRest=1\.25/);
assert.match(game, /const damage=p\.fusionId\?Core\.damageFor\(p\):28/);
assert.match(game, /type:"gasArea"/);
assert.match(game, /color:"#9b63d3"/);
assert.match(game, /color:"#9257c8"/);
assert.match(game, /for\(let i=0;i<72;i\+\+\)\{const progress=/);
assert.match(game, /for\(let i=0;i<80;i\+\+\)\{const a=i\*2\.399/);
assert.match(game, /z\.poison=Math\.max/);
assert.match(game, /GRID\.cw\*1\.5/);
assert.match(game, /GRID\.ch\*1\.5/);
assert.match(game, /function drawRadialPlant\(/);
assert.match(game, /const veteran=\[.*"flyer","pole"/);
assert.doesNotMatch(game, /e\.code==="F3"/);
assert.match(html, /id="timeStopBtn"/);
assert.match(game, /function toggleTimeStop\(\)/);
assert.match(game, /document\.getElementById\("timeStopBtn"\)\.onclick=toggleTimeStop/);
assert.match(game, /state\.timeScale=state\.timeStop \? \.08 : 1/);
assert.match(game, /function chomp\(/);
assert.match(game, /function spikeAttack\(/);
assert.doesNotMatch(game, /art\.(?:plants|zombies|expansion|classic|traits)\.src=/);
assert.match(game, /drawTextEntity\(`我是\$\{name\}`/);
assert.match(game, /drawTextEntity\(ZOMBIE_TEXT\[z\.kind\]/);
assert.match(game, /function updateInheritedTraits\(p,dt,def,hasEnemy\)/);
assert.match(game, /p\.genes\.includes\("devour"\)/);
assert.match(game, /p\.genes\.includes\("ignite"\)/);
assert.match(game, /p\.genes\.includes\("gust"\)/);
assert.match(html, /src\/ultimate-catalog\.js\?v=4\.4\.1/);
assert.match(html, /src\/fusion-catalog\.js\?v=4\.4\.1/);
assert.match(html, /301 种融合与究极植物/);
assert.match(html, /48 种基础植物/);
assert.match(game, /const plantDef = plant => Core\.plantDef\(plant\)/);
assert.match(html, /id="almanacBtn"/);
assert.match(html, /id="almanacPanel"/);
assert.match(html, /id="almanacGrid"/);
assert.match(game, /const almanacPlants=\[/);
assert.match(game, /\.\.\.Object\.values\(Core\.FUSIONS\)/);
assert.match(game, /def\.abilities\?\.ultimate\?"究极配方"/);
assert.match(game, /item\.ultimate\?"究极"/);
assert.match(game, /function renderAlmanac\(\)/);
assert.match(game, /almanacPlants\.length/);
assert.match(html, /id="zombieAlmanacBtn"/);
assert.match(html, /id="zombieAlmanacPanel"/);
assert.match(html, /id="zombieAlmanacGrid"/);
assert.match(html, /data-zombie-filter="air"/);
assert.match(game, /const ZOMBIE_ALMANAC=/);
assert.match(game, /const zombieAlmanacEntries=/);
assert.match(game, /function renderZombieAlmanac\(\)/);
assert.match(game, /function zombieAlmanacCard\(item\)/);
assert.match(game, /document\.getElementById\("zombieAlmanacBtn"\)/);
assert.match(game, /ability\.shotCount/);
assert.match(game, /ability\.backShots/);
assert.match(game, /Array\.from\(\{length:count\},\(_,i\)=>i<backShots\?Math\.PI:0\)/);
assert.match(game, /speed=radial\?305:290/);
assert.match(game, /lineY:radial\?null:launchY/);
assert.match(game, /vy:radial\?Math\.sin\(a\)\*speed:0/);
assert.match(game, /if\(Number\.isFinite\(b\.lineY\)\)b\.y=b\.lineY/);
assert.doesNotMatch(game, /\(i-\(count-1\)\/2\)\*\.035/);
assert.doesNotMatch(game, /c\.y-9\+\(radial\?0:i\*7\)/);
assert.doesNotMatch(game, /vx:270\+i\*18/);
assert.doesNotMatch(game, /vy:\(i-1\)\*22/);
assert.match(game, /b\.bounce&&b\.x<GRID\.x-40/);
assert.match(game, /b\.sunnyGuaranteed/);

console.log(`content tests passed: text rendering + classic/tower modes + 10-card loadout + ${zombieIds.length} zombie types`);
