const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const game = fs.readFileSync(path.join(__dirname, "../src/game.js"), "utf8");
const zombieIds = ["basic", "cone", "bucket", "runner", "paper", "shield", "healer", "football", "balloon", "miner", "dancer", "giant", "imp", "ice", "pole", "flyer"];

assert.match(game, /const BASE_WAVE_SECONDS = 30;/);
assert.match(game, /const SPAWN_GAPS = \[9\.8,9\.2,8\.6,8,7\.4,6\.8,6\.2,5\.7,5\.2,4\.8\];/);
assert.match(game, /state\.zombies\.length<48/);
assert.match(game, /Math\.max\(2\.7,base\*endless\)/);
assert.match(game, /function drawTextEntity\(/);
assert.match(game, /classic-lawn-background\.jpg/);
assert.match(game, /const GRID = \{ x: 259, y: 86, cols: 9, rows: 5, cw: 96\.25, ch: 120\.25 \};/);
assert.doesNotMatch(game, /\(r\+c\)%2/);
assert.match(game, /function drawPlacementPreview\(\)/);
assert.match(game, /"种植预览"/);
assert.match(game, /const ZOMBIE_TEXT=/);
assert.match(game, /我是小推车/);
assert.match(game, /我是阳光/);
assert.match(game, /mowers: \[1,1,1,1,1\]/);
assert.doesNotMatch(game, /补充了一次推土机机会/);
assert.match(game, /spawnTimer: 10/);
assert.match(game, /state\.mowers\[z\.row\]--/);
assert.match(game, /function poolForWave\(wave\)/);
assert.match(game, /state\.gameMode==="classic"&&state\.battleTime>=WAVE_SECONDS\*10/);
assert.match(game, /function winClassic\(\)/);
for (const id of zombieIds) assert.match(game, new RegExp(`${id}:\\{hp:`), `missing zombie definition: ${id}`);
assert.match(game, /const ZOMBIE_POOLS=\[/);
assert.match(game, /const LOADOUT_SIZE = 10;/);
assert.match(game, /confirmPlantsBtn\.disabled=count===0/);
assert.match(game, /pendingLoadout\.length<1\|\|pendingLoadout\.length>LOADOUT_SIZE/);
assert.match(game, /potato:"◆"/);
assert.match(game, /umbrella:"☂"/);
assert.match(game, /for\(let i=0;i<state\.loadout\.length;i\+\+\)/);
assert.match(game, /data-game-mode/);
assert.match(game, /plant && state\.selected/);
assert.match(game, /function fuseSelectedInto\(host\)/);
assert.match(game, /Core\.previewFusion\(donor,host\)/);
assert.match(game, /wave<=ZOMBIE_POOLS\.length/);
assert.match(game, /kind==="pole"&&!z\.vaulted&&target\.baseId!=="tallnut"/);
assert.match(game, /if\(target&&z\.kind==="giant"\)/);
assert.match(game, /z\.slam<=\.56/);
assert.match(game, /dragCell/);
assert.match(game, /function globalFreeze\(/);
assert.match(game, /function supportPulse\(/);
assert.match(game, /Array\.from\(\{length:5\},\(_,i\)=>-Math\.PI\/2\+i\*TAU\/5\)/);
assert.match(game, /Array\.from\(\{length:8\},\(_,i\)=>-Math\.PI\/8\+i\*TAU\/8\)/);
assert.match(game, /rangeBounds:isGloom/);
assert.match(game, /GRID\.cw\*1\.5/);
assert.match(game, /GRID\.ch\*1\.5/);
assert.match(game, /function drawRadialPlant\(/);
assert.match(game, /const veteran=\[.*"flyer","pole"/);
assert.match(game, /e\.code==="F3"/);
assert.match(game, /state\.timeScale=state\.timeStop \? \.08 : 1/);
assert.match(game, /function chomp\(/);
assert.match(game, /function spikeAttack\(/);
assert.doesNotMatch(game, /art\.(?:plants|zombies|expansion|classic|traits)\.src=/);
assert.match(game, /drawTextEntity\(`我是\$\{name\}`/);
assert.match(game, /drawTextEntity\(ZOMBIE_TEXT\[z\.kind\]/);
assert.match(game, /function updateInheritedTraits\(p,dt,def,hasEnemy\)/);
assert.match(game, /p\.genes\.includes\("devour"\)/);
assert.match(game, /p\.genes\.includes\("ignite"\)/);
assert.match(game, /p\.genes\.includes\("gust"\)/);

console.log(`content tests passed: text rendering + classic/tower modes + 10-card loadout + ${zombieIds.length} zombie types`);
