const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const game = fs.readFileSync(path.join(__dirname, "../src/game.js"), "utf8");
const zombieIds = ["basic", "cone", "bucket", "runner", "paper", "shield", "healer", "football", "balloon", "miner", "dancer", "giant", "imp", "ice", "pole", "flyer"];

assert.match(game, /const BASE_WAVE_SECONDS = 30;/);
assert.match(game, /const SPAWN_GAPS = \[9\.8,9\.2,8\.6,8,7\.4,6\.8,6\.2,5\.7,5\.2,4\.8\];/);
assert.match(game, /state\.zombies\.length<48/);
assert.match(game, /Math\.max\(2\.7,base\*endless\)/);
assert.match(game, /groundedWalk/);
assert.match(game, /const stride=walk/);
assert.match(game, /leftLift=Math\.max\(0,stepLift\)/);
assert.match(game, /mowers: \[2,2,2,2,2\]/);
assert.match(game, /spawnTimer: 10/);
assert.match(game, /state\.mowers\[z\.row\]--/);
assert.match(game, /function poolForWave\(wave\)/);
assert.match(game, /state\.gameMode==="classic"&&state\.battleTime>=WAVE_SECONDS\*10/);
assert.match(game, /function winClassic\(\)/);
for (const id of zombieIds) assert.match(game, new RegExp(`${id}:\\{hp:`), `missing zombie definition: ${id}`);
assert.match(game, /const ZOMBIE_POOLS=\[/);
assert.match(game, /const LOADOUT_SIZE = 10;/);
assert.match(game, /for\(let i=0;i<state\.loadout\.length;i\+\+\)/);
assert.match(game, /data-game-mode/);
assert.match(game, /plant && state\.selected/);
assert.match(game, /function fuseSelectedInto\(host\)/);
assert.match(game, /Core\.previewFusion\(donor,host\)/);
assert.match(game, /wave<=ZOMBIE_POOLS\.length/);
assert.match(game, /kind==="pole"&&!z\.vaulted&&target\.baseId!=="tallnut"/);
assert.match(game, /kind==="giant"&&z\.slam>0/);
assert.match(game, /dragCell/);
assert.match(game, /function globalFreeze\(/);
assert.match(game, /function supportPulse\(/);
assert.match(game, /angles=radial\?\[-\.42,-\.21,0,\.21,\.42\]/);
assert.match(game, /const veteran=\[.*"flyer","pole"/);
assert.match(game, /e\.code==="F3"/);
assert.match(game, /state\.timeScale=state\.timeStop \? \.08 : 1/);
assert.match(game, /function chomp\(/);
assert.match(game, /function spikeAttack\(/);
assert.match(game, /classic-plants-atlas\.png/);
assert.match(game, /fusion-traits-atlas-v2\.png/);
assert.match(game, /function drawFusionTraits\(p\)/);
assert.match(game, /function updateInheritedTraits\(p,dt,def,hasEnemy\)/);
assert.match(game, /p\.genes\.includes\("devour"\)/);
assert.match(game, /p\.genes\.includes\("ignite"\)/);
assert.match(game, /p\.genes\.includes\("gust"\)/);

console.log(`content tests passed: classic/tower modes + 10-card loadout + ${zombieIds.length} zombie types`);
